<a href="https://colab.research.google.com/github/k-jinwoo/Colab/blob/main/2_Numpy_%EC%8B%A4%EC%8A%B5%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/07/05
이름 : 김진우
내용 : 파이썬 Numpy 패키지 실습하기
"""
import numpy as np

In [ ]:
# numpy 자료구조 - 벡터
v1 = np.array([1,2,3,4,5])
print("v1 : ",v1)

v2 = np.arange(5)
print('v2 : ',v2)

v3 = np.arange(10)
print('v3 : ',v3)

v1 :  [1 2 3 4 5]
v2 :  [0 1 2 3 4]
v3 :  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0 - 1 사이의 임의의 실수 100개
rand1 = np.random.rand(100)
print(rand1)

# 표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
print(rand2)

# 0 - 9 사이의 임의의 정수


[0.70278485 0.38109396 0.36063181 0.78274966 0.4173572  0.93311784
 0.4595312  0.82331273 0.69292877 0.72994433 0.667748   0.66707997
 0.32767427 0.32174444 0.20570909 0.33560109 0.86211397 0.65528
 0.28225351 0.25837353 0.22344226 0.50483716 0.10574452 0.78332535
 0.04088694 0.17632341 0.28632178 0.8295424  0.86745669 0.03140453
 0.39163898 0.31054447 0.54779475 0.48401244 0.87988346 0.06126888
 0.19534053 0.98876273 0.21090676 0.97043021 0.14513211 0.60855107
 0.25356801 0.40316562 0.6363343  0.02248486 0.44576654 0.46589973
 0.84702401 0.21687269 0.55845042 0.8794467  0.61032316 0.85344958
 0.85151835 0.84140075 0.42586464 0.92534751 0.66884662 0.95655279
 0.43589472 0.46565677 0.3979531  0.40639486 0.85430776 0.71173149
 0.5679413  0.70581291 0.47979154 0.57315929 0.32806457 0.41810417
 0.39032078 0.36301689 0.95304198 0.23801693 0.37530072 0.07108222
 0.07346081 0.44850433 0.6805534  0.21488667 0.74516806 0.64291892
 0.22427432 0.88993847 0.87687172 0.2319012  0.94150147 0.0024474

In [ ]:
# numpy 자료구조 - 행렬
m1 = np.array([[1,2],[3,4]])
print(m1)

m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m2)

m3 = np.ones([2,4])
print(m3)

m4 = np.zeros([3,2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# 전치 행렬
print(m1.T)

print(m2.transpose())

[[1 3]
 [2 4]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 단위 행렬
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 역 행렬
im1 = np.linalg.inv(m1)
print(im1)

print(im1 * im1)

result = m1.dot(im1)
print(result.round())

[[-2.   1. ]
 [ 1.5 -0.5]]
[[4.   1.  ]
 [2.25 0.25]]
[[1. 0.]
 [0. 1.]]


In [ ]:
# 행렬 인덱싱
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)

print(matrix[0, 0])
print(matrix[0, :])
print(matrix[:, 0])

print(matrix[0:2, 0:2])
print(matrix[:, 0:2])
print(matrix[:, 2:4])
print(matrix[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
